<a href="https://colab.research.google.com/github/harshit-ag14/Machine-Learning/blob/main/Iris_LAB_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Iris- LAB 1.ipynb***


In [1]:
import numpy as np
import pandas as pd
import sklearn


In [2]:
from google.colab import files
uploaded = files.upload()

Saving IRIS_dataset.csv to IRIS_dataset.csv


In [3]:
dataset = pd.read_csv('IRIS_dataset.csv')

In [4]:
print (dataset)

    sepal_length  sepal_width  petal_length  petal_width     flower
0            5.1          3.5           1.4          0.2     setosa
1            4.9          3.0           1.4          0.2     setosa
2            4.7          3.2           1.3          0.2     setosa
3            4.6          3.1           1.5          0.2     setosa
4            5.0          3.6           1.4          0.2     setosa
..           ...          ...           ...          ...        ...
95           7.2          3.0           5.8          1.6  virginica
96           7.4          2.8           6.1          1.9  virginica
97           7.9          3.8           6.4          2.0  virginica
98           6.4          2.8           5.6          2.2  virginica
99           6.3          2.8           5.1          1.5  virginica

[100 rows x 5 columns]


In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  100 non-null    float64
 1   sepal_width   100 non-null    float64
 2   petal_length  100 non-null    float64
 3   petal_width   100 non-null    float64
 4   flower        100 non-null    object 
dtypes: float64(4), object(1)
memory usage: 4.0+ KB


In [6]:
dataset.isnull()

sepal_length  sepal_width  petal_length  petal_width  flower
0          False        False         False        False   False
1          False        False         False        False   False
2          False        False         False        False   False
3          False        False         False        False   False
4          False        False         False        False   False
..           ...          ...           ...          ...     ...
95         False        False         False        False   False
96         False        False         False        False   False
97         False        False         False        False   False
98         False        False         False        False   False
99         False        False         False        False   False

[100 rows x 5 columns]

In [7]:
dataset.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
flower          0
dtype: int64

In [8]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width  flower
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
dataset.tail()

sepal_length  sepal_width  petal_length  petal_width     flower
95           7.2          3.0           5.8          1.6  virginica
96           7.4          2.8           6.1          1.9  virginica
97           7.9          3.8           6.4          2.0  virginica
98           6.4          2.8           5.6          2.2  virginica
99           6.3          2.8           5.1          1.5  virginica

In [10]:
X=dataset.drop(['flower'], axis=1)

In [11]:
print (X)

    sepal_length  sepal_width  petal_length  petal_width
0            5.1          3.5           1.4          0.2
1            4.9          3.0           1.4          0.2
2            4.7          3.2           1.3          0.2
3            4.6          3.1           1.5          0.2
4            5.0          3.6           1.4          0.2
..           ...          ...           ...          ...
95           7.2          3.0           5.8          1.6
96           7.4          2.8           6.1          1.9
97           7.9          3.8           6.4          2.0
98           6.4          2.8           5.6          2.2
99           6.3          2.8           5.1          1.5

[100 rows x 4 columns]


In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
Y=dataset['flower']

In [14]:
Y.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [15]:
lb1 = LabelEncoder()
dataset['flower'] = lb1.fit_transform(Y)

In [16]:
Y = dataset['flower']

In [17]:
Y

0     0
1     0
2     0
3     0
4     0
     ..
95    2
96    2
97    2
98    2
99    2
Name: flower, Length: 100, dtype: int64

In [18]:
Y.unique()

array([0, 1, 2])

In [19]:

X.shape, Y.shape

((100, 4), (100,))

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 25)

In [22]:
x_train.shape, y_train.shape

((80, 4), (80,))

In [23]:
x_test.shape, y_test.shape

((20, 4), (20,))

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
model = LogisticRegression(max_iter=150)
model = model.fit(x_train, y_train)

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix, mean_squared_error

In [27]:
train_accuracy = model.score(x_train, y_train)

In [28]:
print ('Accuracy', train_accuracy)

Accuracy 0.95


In [29]:
predict = model.predict(x_test)

In [30]:
model.score(x_test, y_test)

0.85

In [31]:
accuracy_score(y_test, predict)

0.85

In [32]:
print(confusion_matrix(y_test, predict))

[[3 0 0]
 [0 6 2]
 [0 1 8]]


***By Harshit Agarwal 20BCB7071*** 