<a href="https://colab.research.google.com/github/harshit-ag14/Machine-Learning/blob/main/LAB2_IRIS_KNeighborsClassifier__.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***IRIS KNeighborsClassifier-LAB2.ipynb***

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
from google.colab import files
uploaded = files.upload()

Saving IRIS_dataset.csv to IRIS_dataset.csv


In [3]:
dataset=pd.read_csv('IRIS_dataset.csv')

In [4]:
print(dataset)

    sepal_length  sepal_width  petal_length  petal_width     flower
0            5.1          3.5           1.4          0.2     setosa
1            4.9          3.0           1.4          0.2     setosa
2            4.7          3.2           1.3          0.2     setosa
3            4.6          3.1           1.5          0.2     setosa
4            5.0          3.6           1.4          0.2     setosa
..           ...          ...           ...          ...        ...
95           7.2          3.0           5.8          1.6  virginica
96           7.4          2.8           6.1          1.9  virginica
97           7.9          3.8           6.4          2.0  virginica
98           6.4          2.8           5.6          2.2  virginica
99           6.3          2.8           5.1          1.5  virginica

[100 rows x 5 columns]


In [5]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width  flower
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  100 non-null    float64
 1   sepal_width   100 non-null    float64
 2   petal_length  100 non-null    float64
 3   petal_width   100 non-null    float64
 4   flower        100 non-null    object 
dtypes: float64(4), object(1)
memory usage: 4.0+ KB


In [7]:
dataset.isnull()

sepal_length  sepal_width  petal_length  petal_width  flower
0          False        False         False        False   False
1          False        False         False        False   False
2          False        False         False        False   False
3          False        False         False        False   False
4          False        False         False        False   False
..           ...          ...           ...          ...     ...
95         False        False         False        False   False
96         False        False         False        False   False
97         False        False         False        False   False
98         False        False         False        False   False
99         False        False         False        False   False

[100 rows x 5 columns]

In [8]:
dataset.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
flower          0
dtype: int64

In [9]:
X=dataset.drop(['flower'],axis=1)

In [10]:
print(X)

    sepal_length  sepal_width  petal_length  petal_width
0            5.1          3.5           1.4          0.2
1            4.9          3.0           1.4          0.2
2            4.7          3.2           1.3          0.2
3            4.6          3.1           1.5          0.2
4            5.0          3.6           1.4          0.2
..           ...          ...           ...          ...
95           7.2          3.0           5.8          1.6
96           7.4          2.8           6.1          1.9
97           7.9          3.8           6.4          2.0
98           6.4          2.8           5.6          2.2
99           6.3          2.8           5.1          1.5

[100 rows x 4 columns]


In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
Y=dataset['flower']

In [13]:
print(Y)

0        setosa
1        setosa
2        setosa
3        setosa
4        setosa
        ...    
95    virginica
96    virginica
97    virginica
98    virginica
99    virginica
Name: flower, Length: 100, dtype: object


In [14]:
Y.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [15]:
X.shape, Y.shape

((100, 4), (100,))

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20,random_state=25)

In [17]:
X_train.shape, Y_train.shape

((80, 4), (80,))

In [18]:
X_test.shape, Y_test.shape

((20, 4), (20,))

In [19]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, Y_train)

KNeighborsClassifier()

In [20]:
train_accuracy = classifier.score(X_train, Y_train)
print ('Accuracy', train_accuracy)

Accuracy 0.9875


In [21]:
Y_pred = classifier.predict(X_test)

In [22]:
classifier.score(X_test, Y_test)

0.9

In [23]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [24]:
accuracy_score(Y_test, Y_pred)

0.9

In [25]:
result = confusion_matrix(Y_test, Y_pred)
print("Confusion Matrix:")
print(result)

Confusion Matrix:
[[3 0 0]
 [0 7 1]
 [0 1 8]]


In [26]:
new_input=[[4.4,2.9,1.4,0.2]]
new_output=classifier.predict(new_input)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


In [27]:
print(new_output)

['setosa']


***By Harshit Agarwal 20BCB7071***