<a href="https://colab.research.google.com/github/harshit-ag14/ML/blob/main/MNIST_LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import sklearn

In [4]:
from google.colab import files
uploaded = files.upload()

Saving mnist_submission.csv to mnist_submission.csv


In [5]:
dataset= pd.read_csv('mnist_submission.csv')

In [6]:
print(dataset)

       ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      9
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]


In [7]:
dataset.head()

ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3

In [8]:
dataset.tail()

ImageId  Label
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

In [9]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28000 entries, 0 to 27999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ImageId  28000 non-null  int64
 1   Label    28000 non-null  int64
dtypes: int64(2)
memory usage: 437.6 KB


In [10]:
dataset.isnull()

ImageId  Label
0        False  False
1        False  False
2        False  False
3        False  False
4        False  False
...        ...    ...
27995    False  False
27996    False  False
27997    False  False
27998    False  False
27999    False  False

[28000 rows x 2 columns]

In [11]:
dataset.isnull().sum()

ImageId    0
Label      0
dtype: int64

In [12]:
X=dataset.drop(['Label'], axis=1)

In [13]:
print(X)

       ImageId
0            1
1            2
2            3
3            4
4            5
...        ...
27995    27996
27996    27997
27997    27998
27998    27999
27999    28000

[28000 rows x 1 columns]


In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
Y=dataset['Label']

In [16]:
Y.unique()

array([2, 0, 9, 3, 7, 5, 4, 1, 6, 8])

In [17]:
lb1 = LabelEncoder()
dataset['Label'] = lb1.fit_transform(Y)

In [18]:
Y.unique()

array([2, 0, 9, 3, 7, 5, 4, 1, 6, 8])

In [19]:
X.shape, Y.shape

((28000, 1), (28000,))

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 22000)

In [22]:
x_train.shape, y_train.shape

((21000, 1), (21000,))

In [23]:
x_test.shape, y_test.shape

((7000, 1), (7000,))

In [24]:
from sklearn.linear_model import LogisticRegression

In [26]:
model = LogisticRegression(C=0.1, max_iter=28000)
model = model.fit(x_train, y_train)

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix, mean_squared_error

In [28]:
train_accuracy = model.score(x_train, y_train)

In [29]:
print ('Accuracy', train_accuracy)

Accuracy 0.114


In [30]:
predict = model.predict(x_test)

In [31]:
model.score(x_test, y_test)

0.11657142857142858

In [32]:
accuracy_score(y_test, predict)

0.11657142857142858

In [33]:
print(confusion_matrix(y_test, predict))

[[  0 745   0   0   0   0   0   0   0   0]
 [  0 816   0   0   0   0   0   0   0   0]
 [  0 668   0   0   0   0   0   0   0   0]
 [  0 714   0   0   0   0   0   0   0   0]
 [  0 690   0   0   0   0   0   0   0   0]
 [  0 583   0   0   0   0   0   0   0   0]
 [  0 679   0   0   0   0   0   0   0   0]
 [  0 743   0   0   0   0   0   0   0   0]
 [  0 667   0   0   0   0   0   0   0   0]
 [  0 695   0   0   0   0   0   0   0   0]]


***By Harshit Agarwal 20BCB7071***